# Vivado Synthesis Script for PDQAP Solver (Cached)
# Generated by generate_cached.py

create_project pdaqp_cached /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/vivado_project -part xczu7ev-ffvc1156-2-e -force

# Add RTL files
add_files [glob /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/rtl/*.v]

set_property top pdaqp_top [current_fileset]

# Add include directory
set_property include_dirs {/mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/include} [current_fileset]

# Synthesis strategy
set_property strategy Flow_PerfOptimized_high [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.DIRECTIVE PerformanceOptimized [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.RETIMING true [get_runs synth_1]

# Launch synthesis
launch_runs synth_1 -jobs 8
wait_on_run synth_1

# Generate reports
file mkdir /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/reports
open_run synth_1
report_utilization -file /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/reports/utilization.rpt
report_timing_summary -file /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/reports/timing.rpt
report_power -file /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/reports/power.rpt

puts "Synthesis complete. Reports saved to /mnt/c/Users/zhaoj/Desktop/HWGen/cvxpygen/HWGen/codegen_pdaqp_cached/reports/"
