"""
distance_checker.py
===================
Fixed-Point Euclidean Distance Checker for Cached BST Solver

Computes squared Euclidean distance between query point and candidate solution:
    dist² = Σ(query[i] - solution[i])²

Features:
- Parallel computation pipeline
- Fixed-point arithmetic (format from config.vh)
- Pipelined multiply-accumulate (MAC)
- Configurable precision
"""

from pathlib import Path
from typing import Dict, Any, Optional
import re


class DistanceCheckerGenerator:
    """Generate distance checker module for fixed-point arithmetic"""
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize distance checker generator
        
        Args:
            config: Solver configuration containing:
                - n_parameters: Number of parameters (m)
                - data_format: e.g. "FIX16", "FIX32"
                - int_bits: Integer bits (from config.vh)
                - frac_bits: Fractional bits (from config.vh)
                - data_width: Total width (int_bits + frac_bits + 1 sign bit)
                - project_name: Design name
        """
        self.config = config
        self.m = config['n_parameters']
        
        # Read Q format from config
        self.int_bits = config.get('int_bits')
        self.frac_bits = config.get('frac_bits')
        
        if self.int_bits is None or self.frac_bits is None:
            raise ValueError("int_bits and frac_bits must be specified in config")
        
        # Total width = sign bit + integer bits + fractional bits
        self.data_width = 1 + self.int_bits + self.frac_bits
        
        self.project_name = config.get('project_name', 'solver')
        
        # Pipeline configuration
        self.pipeline_stages = self._calculate_pipeline_stages()
        
        # Internal precision for intermediate products
        # Product of two Q_int.frac numbers gives Q_(2*int).(2*frac)
        self.product_width = 2 * self.data_width
        self.product_int_bits = 2 * self.int_bits + 1  # +1 for sign extension
        self.product_frac_bits = 2 * self.frac_bits
        
        # Accumulator needs extra bits for sum of m products
        self.accumulator_width = self.product_width + self._bits_needed(self.m)
    
    def _bits_needed(self, n: int) -> int:
        """Calculate bits needed to represent sum of n values"""
        if n <= 1:
            return 0
        return (n - 1).bit_length()
    
    def _calculate_pipeline_stages(self) -> int:
        """Determine optimal pipeline stages based on parameter count"""
        if self.m <= 2:
            return 2  # subtract + accumulate
        elif self.m <= 4:
            return 3  # subtract + multiply + accumulate
        else:
            return 4  # subtract + multiply + partial_sum + final_sum
    
    def generate(self, output_dir: str) -> str:
        """
        Generate distance checker Verilog module
        
        Returns:
            Path to generated file
        """
        output_path = Path(output_dir) / f'{self.project_name}_distance_checker.v'
        
        verilog = self._generate_module()
        
        with open(output_path, 'w') as f:
            f.write(verilog)
        
        return str(output_path)
    
    def _generate_module(self) -> str:
        """Generate complete Verilog module"""
        return f"""{self._file_header()}

`include "config.vh"

module {self.project_name}_distance_checker #(
    parameter M = {self.m}                     // Number of parameters
) (
    input  wire clk,
    input  wire rst_n,
    
    // Control
    input  wire start,              // Start distance computation
    output reg  valid,              // Distance result valid
    output reg  busy,               // Computation in progress
    
    // Query point input (from cache or registers)
    input  wire [`DATA_WIDTH-1:0] query [0:M-1],
    
    // Candidate solution input (from cache)
    input  wire [`DATA_WIDTH-1:0] solution [0:M-1],
    
    // Distance output (squared distance in fixed-point)
    // Format: Q{2*self.int_bits+1}.{2*self.frac_bits} (squared result doubles fractional bits)
    output reg  [{self.accumulator_width-1}:0] distance_sq
);

{self._generate_internal_signals()}

{self._generate_control_logic()}

{self._generate_datapath()}

endmodule
"""
    
    def _file_header(self) -> str:
        """Generate file header"""
        q_format = f"Q{self.int_bits}.{self.frac_bits}"
        q_product_format = f"Q{self.product_int_bits}.{self.product_frac_bits}"
        
        return f"""//==============================================================================
// Distance Checker Module - Fixed-Point Euclidean Distance
//==============================================================================
// Auto-generated by CachedBSTSolver
//
// Computes squared Euclidean distance between query and candidate:
//     dist² = Σ(query[i] - solution[i])²
//
// Configuration:
//   Parameters:       {self.m}
//   Input format:     {q_format} ({self.data_width} bits)
//   Product format:   {q_product_format} ({self.product_width} bits)
//   Accumulator:      {self.accumulator_width} bits
//   Pipeline stages:  {self.pipeline_stages}
//
// Latency: {self.pipeline_stages + 1} cycles
//
// Note: Result is in Q{self.product_int_bits}.{self.product_frac_bits} format
//       (squaring doubles the fractional bits)
//==============================================================================
"""
    
    def _generate_internal_signals(self) -> str:
        """Generate internal signal declarations"""
        product_width = self.product_width
        accum_width = self.accumulator_width
        
        signals = f"""    // Configuration from config.vh
    localparam DATA_WIDTH = `DATA_WIDTH;           // Total width
    localparam INT_BITS = `INT_BITS;               // Integer bits
    localparam FRAC_BITS = `FRAC_BITS;             // Fractional bits
    
    // Derived parameters
    localparam PRODUCT_WIDTH = 2 * DATA_WIDTH;     // Product width
    localparam ACCUM_WIDTH = {accum_width};        // Accumulator width
    
    // Pipeline stage signals
    reg  [DATA_WIDTH-1:0] diff_stage [0:M-1];           // Stage 1: differences
    reg  [PRODUCT_WIDTH-1:0] product_stage [0:M-1];     // Stage 2: squared differences
    reg  [ACCUM_WIDTH-1:0] partial_sum_stage;           // Stage 3: partial sum (if needed)
    reg  [ACCUM_WIDTH-1:0] accumulator;                 // Final accumulator
    
    // Pipeline valid tracking
    reg  [{self.pipeline_stages}:0] valid_pipe;
    
    // State for pipelined operation
    reg  computing;
    
    // Helper signals for subtraction (extended for overflow detection)
    wire signed [DATA_WIDTH:0] diff_extended [0:M-1];
"""
        
        return signals
    
    def _generate_control_logic(self) -> str:
        """Generate FSM control logic"""
        return f"""    //==========================================================================
    // Control Logic - Pipeline Management
    //==========================================================================
    
    localparam PIPE_DEPTH = {self.pipeline_stages};
    
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            computing <= 1'b0;
            busy <= 1'b0;
            valid <= 1'b0;
            valid_pipe <= '0;
        end else begin
            // Start new computation
            if (start && !busy) begin
                computing <= 1'b1;
                busy <= 1'b1;
                valid <= 1'b0;
                valid_pipe <= {{{{1'b1, {{PIPE_DEPTH{{1'b0}}}}}}}};
            end
            // Pipeline advance
            else if (computing) begin
                valid_pipe <= {{valid_pipe[PIPE_DEPTH-1:0], 1'b0}};
                
                // Check if pipeline completed
                if (valid_pipe[PIPE_DEPTH]) begin
                    valid <= 1'b1;
                    busy <= 1'b0;
                    computing <= 1'b0;
                end
            end
            // Clear valid after one cycle
            else if (valid) begin
                valid <= 1'b0;
            end
        end
    end
"""
    
    def _generate_datapath(self) -> str:
        """Generate computational datapath"""
        
        stage1 = self._generate_stage1_subtraction()
        stage2 = self._generate_stage2_multiplication()
        stage3 = self._generate_stage3_accumulation()
        stage4 = self._generate_stage4_output()
        
        return f"""    //==========================================================================
    // Datapath - Pipelined Distance Computation
    //==========================================================================
    
{stage1}

{stage2}

{stage3}

{stage4}
"""
    
    def _generate_stage1_subtraction(self) -> str:
        """Generate Stage 1: Compute differences"""
        code = """    // Stage 1: Compute differences (query[i] - solution[i])
    //--------------------------------------------------------------------------
    // Format preservation: Q_int.frac - Q_int.frac = Q_int.frac
    genvar i;
    generate
        for (i = 0; i < M; i = i + 1) begin : gen_diff
            // Sign-extend for overflow detection
            assign diff_extended[i] = $signed({query[i][DATA_WIDTH-1], query[i]}) - 
                                     $signed({solution[i][DATA_WIDTH-1], solution[i]});
        end
    endgenerate
    
    always @(posedge clk) begin
        if (start || computing) begin
            for (integer j = 0; j < M; j = j + 1) begin
                // Check for overflow (sign bit mismatch with MSB)
                if (diff_extended[j][DATA_WIDTH] != diff_extended[j][DATA_WIDTH-1]) begin
                    // Overflow: saturate to max/min value
                    diff_stage[j] <= diff_extended[j][DATA_WIDTH] ? 
                                    {1'b1, {(DATA_WIDTH-1){1'b0}}} :  // Most negative
                                    {1'b0, {(DATA_WIDTH-1){1'b1}}};   // Most positive
                end else begin
                    // Normal case: truncate to DATA_WIDTH
                    diff_stage[j] <= diff_extended[j][DATA_WIDTH-1:0];
                end
            end
        end
    end
"""
        return code
    
    def _generate_stage2_multiplication(self) -> str:
        """Generate Stage 2: Square the differences"""
        
        code = f"""    // Stage 2: Square differences (diff[i] * diff[i])
    //--------------------------------------------------------------------------
    // Format: Q_int.frac * Q_int.frac = Q_(2*int+1).(2*frac)
    // Product width = 2 * DATA_WIDTH
    always @(posedge clk) begin
        if (computing) begin
            for (integer j = 0; j < M; j = j + 1) begin
                // Signed multiplication using DSP blocks
                product_stage[j] <= $signed(diff_stage[j]) * $signed(diff_stage[j]);
            end
        end
    end
"""
        return code
    
    def _generate_stage3_accumulation(self) -> str:
        """Generate Stage 3: Accumulate squared differences"""
        
        if self.m <= 4:
            # Small parameter count: direct sum
            return self._generate_direct_sum()
        else:
            # Large parameter count: tree reduction
            return self._generate_tree_reduction()
    
    def _generate_direct_sum(self) -> str:
        """Direct summation for small M"""
        
        code = f"""    // Stage 3: Accumulate (direct sum for M <= 4)
    //--------------------------------------------------------------------------
    // Sum all squared differences
    always @(posedge clk) begin
        if (computing && valid_pipe[1]) begin
            accumulator <= """
        
        # Generate sum expression
        sum_terms = []
        for i in range(self.m):
            sum_terms.append(f"product_stage[{i}]")
        
        code += " + \n                           ".join(sum_terms) + """;
        end
    end
"""
        return code
    
    def _generate_tree_reduction(self) -> str:
        """Tree reduction for large M"""
        num_level1 = (self.m + 1) // 2
        
        code = f"""    // Stage 3: Accumulate (tree reduction for M > 4)
    //--------------------------------------------------------------------------
    // Use tree structure to minimize critical path and improve timing
    reg  [ACCUM_WIDTH-1:0] level1_sum [0:{num_level1-1}];
    
    always @(posedge clk) begin
        if (computing && valid_pipe[1]) begin
            // Level 1: Pairwise addition
"""
        
        # Generate pairwise sums
        for i in range(0, self.m, 2):
            if i + 1 < self.m:
                code += f"            level1_sum[{i//2}] <= product_stage[{i}] + product_stage[{i+1}];\n"
            else:
                code += f"            level1_sum[{i//2}] <= product_stage[{i}];\n"
        
        code += """        end
        
        if (computing && valid_pipe[2]) begin
            // Level 2: Final sum of level1 results
            partial_sum_stage <= """
        
        # Sum all level1 results
        level1_terms = [f"level1_sum[{i}]" for i in range(num_level1)]
        code += " + \n                                     ".join(level1_terms) + """;
        end
        
        if (computing && valid_pipe[3]) begin
            // Transfer to accumulator
            accumulator <= partial_sum_stage;
        end
    end
"""
        return code
    
    def _generate_stage4_output(self) -> str:
        """Generate Stage 4: Output result"""
        return f"""    // Stage 4: Output
    //--------------------------------------------------------------------------
    always @(posedge clk) begin
        if (computing && valid_pipe[{self.pipeline_stages}]) begin
            // Output accumulated squared distance
            // Format: Q{self.product_int_bits}.{self.product_frac_bits}
            // (squaring doubles the fractional bits: 2*FRAC_BITS)
            distance_sq <= accumulator;
        end
    end
"""
    
    def get_latency(self) -> int:
        """Return pipeline latency in cycles"""
        return self.pipeline_stages + 1
    
    def get_resource_estimate(self) -> Dict[str, int]:
        """Estimate FPGA resource usage"""
        
        # Multipliers (DSP blocks) - one per parameter
        multipliers = self.m
        
        # Adders (LUTs) - for accumulation tree
        if self.m <= 4:
            adders = self.m - 1  # Direct sum
            adder_width = self.product_width
        else:
            # Tree reduction
            level1_adders = (self.m + 1) // 2
            level2_adders = level1_adders - 1
            adders = level1_adders + level2_adders
            adder_width = self.accumulator_width
        
        # Registers (FFs)
        diff_regs = self.m * self.data_width
        product_regs = self.m * self.product_width
        accum_regs = self.accumulator_width
        control_regs = 16  # Control signals
        
        if self.m > 4:
            partial_regs = ((self.m + 1) // 2) * self.accumulator_width
        else:
            partial_regs = 0
        
        total_regs = diff_regs + product_regs + accum_regs + control_regs + partial_regs
        
        return {
            'DSP_blocks': multipliers,
            'Adders_LUT': adders * (adder_width // 4),  # Rough: 0.25 LUT per adder bit
            'Registers_FF': total_regs,
            'Latency_cycles': self.get_latency(),
            'Max_frequency_est_MHz': 200  # Conservative estimate
        }
    
    def get_format_info(self) -> Dict[str, Any]:
        """Return fixed-point format information"""
        return {
            'input_format': f'Q{self.int_bits}.{self.frac_bits}',
            'input_width': self.data_width,
            'product_format': f'Q{self.product_int_bits}.{self.product_frac_bits}',
            'product_width': self.product_width,
            'accumulator_width': self.accumulator_width,
            'output_format': f'Q{self.product_int_bits}.{self.product_frac_bits}'
        }


# Factory function
def create_distance_checker(config: Dict[str, Any]) -> DistanceCheckerGenerator:
    """
    Factory function to create distance checker generator
    
    Args:
        config: Configuration dictionary with int_bits and frac_bits
        
    Returns:
        DistanceCheckerGenerator instance
    """
    return DistanceCheckerGenerator(config)


# Example usage
if __name__ == '__main__':
    # Test configuration - Q format from config.vh
    test_config = {
        'n_parameters': 3,
        'data_format': 'FIX16',
        'int_bits': 7,      # From config.vh INT_BITS
        'frac_bits': 8,     # From config.vh FRAC_BITS
        'project_name': 'test_solver'
    }
    
    generator = create_distance_checker(test_config)
    
    print("Distance Checker Configuration:")
    print(f"  Parameters (m): {generator.m}")
    format_info = generator.get_format_info()
    print(f"  Input format: {format_info['input_format']} ({format_info['input_width']} bits)")
    print(f"  Product format: {format_info['product_format']} ({format_info['product_width']} bits)")
    print(f"  Output format: {format_info['output_format']} ({format_info['accumulator_width']} bits)")
    print(f"  Pipeline stages: {generator.pipeline_stages}")
    print(f"  Latency: {generator.get_latency()} cycles")
    
    print("\nResource Estimates:")
    resources = generator.get_resource_estimate()
    for key, value in resources.items():
        print(f"  {key}: {value}")
    
    # Generate module
    output = generator.generate('.')
    print(f"\nGenerated: {output}")